### ISSUE TITLE
Exception in valid_ip

### ISSUE THREAD

**Issue by testeib02** [flatsiedatsie/webthings-network-presence-detection#18]
If there is exactly 3 dots in my hostname with domain name, the valid_ip() checking will fail.
For example, myhostname.lan.mydomain.com

```
2019-12-02 14:45:02.029 ERROR  : network-presence-detection: Exception in thread Thread-135:
2019-12-02 14:45:02.029 ERROR  : network-presence-detection: Traceback (most recent call last):
2019-12-02 14:45:02.030 ERROR  : network-presence-detection:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
2019-12-02 14:45:02.031 ERROR  : network-presence-detection:     self.run()
2019-12-02 14:45:02.031 ERROR  : network-presence-detection:   File "/usr/lib/python3.7/threading.py", line 865, in run
2019-12-02 14:45:02.032 ERROR  : network-presence-detection:     self._target(*self._args, **self._kwargs)
2019-12-02 14:45:02.032 ERROR  : network-presence-detection:   File "/home/pi/.mozilla-iot/addons/network-presence-detection-adapter/pkg/presence_adapter.py", line 260, in scan
2019-12-02 14:45:02.033 ERROR  : network-presence-detection:     if found_device_name == '?' or valid_ip(found_device_name):
2019-12-02 14:45:02.033 ERROR  : network-presence-detection:   File "/home/pi/.mozilla-iot/addons/network-presence-detection-adapter/pkg/util.py", line 10, in valid_ip
2019-12-02 14:45:02.034 ERROR  : network-presence-detection:     all(0 <= int(num) < 256 for num in ip.rstrip().split('.'))
2019-12-02 14:45:02.034 ERROR  : network-presence-detection:   File "/home/pi/.mozilla-iot/addons/network-presence-detection-adapter/pkg/util.py", line 10, in <genexpr>
2019-12-02 14:45:02.035 ERROR  : network-presence-detection:     all(0 <= int(num) < 256 for num in ip.rstrip().split('.'))
2019-12-02 14:45:02.036 ERROR  : network-presence-detection: ValueError: invalid literal for int() with base 10: 'myhostname'

```

**Comment by flatsiedatsie** [comment]
Thanks. This will be fixed in the next version. Should be released soon.
