### ISSUE TITLE
Functions missing in util.py

### ISSUE THREAD

**Issue by mrstegeman** [flatsiedatsie/webthings-network-presence-detection#2]
```
2019-04-30 10:42:34.957 ERROR  : network-presence-detection: Traceback (most recent call last):
2019-04-30 10:42:34.958 ERROR  : network-presence-detection:   File "/Users/mstegeman/.mozilla-iot/addons/network-presence-detection-adapter/main.py", line 12, in <module>
2019-04-30 10:42:34.958 ERROR  : network-presence-detection:     from pkg.presence_adapter import presenceAdapter  # noqa
2019-04-30 10:42:34.958 ERROR  : network-presence-detection:   File "/Users/mstegeman/workspace/adapters/network-presence-detection/pkg/presence_adapter.py", line 14, in <module>
2019-04-30 10:42:34.958 ERROR  : network-presence-detection:     from .util import validip, clamp
2019-04-30 10:42:34.958 ERROR  : network-presence-detection: ImportError: cannot import name 'validip' from 'pkg.util' (/Users/mstegeman/workspace/adapters/network-presence-detection/pkg/util.py)
```

**Comment by flatsiedatsie** [comment]
I have no idea how hat got mixed up. It's fixed now though.
